### ISSUE TITLE
Embeddings Service

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/apollo#111]
We need to integrate a generic embeddings layer into Apollo.

At the moment, provide a search service which embeds the docsite - see #98 for outstanding work there.

But I'd like an architecture where any apollo service can access embeddings via a simple API

# API

The server needs an internal service like `embed`.

This should expose python services which can be called from the command line. It probably need an API like:

```
embed(datasetName, listOfChunks)
search(datasetName, query)
```

Where each chunk is probably a string.

We should not provide a direct REST API.

I think embeddings should be populated during the image build. So we need to work out a way for scripts to run at build time. Maybe every module can provide a build.py or build.sh which is automatically called by the build process

# Integrations

* The existing doc search is built on Milvus and Zilliz. It has a script to scrape the docsite and submit embeddings. It's a great reference and starting point, and when this work is done,  the search service should be ported over to it.
* The new mapping service will use this to embed vocabularies. It will probably be our first client

# Implementation Plan

The first step is to pick a suitable third party embedding service and database. There are many candidates for this.

The service should totally abstract the implementation, so that we can switch embedding services without affecting any of the dependent services

We should move all the vector DB and embedding client logic out of the docs embedding script. The docs script should call into the new embedding API, but not make any decisions itself about what database or embedding service to use.

Later, we can investigate the cost of hosting our own embeddings service. It would be super useful to handle user queries and support the AI assistant and stuff without calling out to a third party server.

**Comment by josephjclark** [comment]
@elias-ba would you be up for leading a survey of vector databases and/or embeddings services? I know Anthropic recommend voyage.ai. 

We need to design this service so that we're not locked to any particular vendor, but we need to start somewhere.

I presume embeddings models aren't all born equal. How do we know a good one? Do we need to optimise for a particular domain?

**Comment by josephjclark** [comment]
At the moment, every build will clear the embeddiungs in the zilliz database. But the build and production use the same database! So we need to do something to decouple this. Maybe we create a new database with a build name?

Or we have build and embed as totally separate processes

**Comment by josephjclark** [comment]
* What model and how is it trained
* Community around it
* Can we self-host or download or own version?
* Cost?
* Any kind of tech4good license we can take advantage of?

**Comment by elias-ba** [comment]
Hey @josephjclark, I really enjoyed this assignment, thank you! I've shared the survey results in a Google Doc. I am wondering if I should link the doc here or not, let me know. @hanna-paasivirta and I had a quick discussion about it. As always, I’m available to refine this further or support with any additional assignments that could help. Cheers 🍻

**Comment by josephjclark** [comment]
Thank you @elias-ba ! A link to the doc here would be great. I'll sync up with you later in the week

**Comment by josephjclark** [comment]
The service so far looks very flexible, we can support multiple embeddings and databases. Very open.

Database:

I'd like Apollo to pick a standard vector DB and interface to it.

pgvector sounds like the one for us. We'd need to work out hosting. Maybe Elias can help us with that.

In the short term, we will build the mappings project on zilliz and milvus.

Embeddings:

We'll need to support multiple embeddings, so keep that loose. It doesn't make sense to have a standard embeddings service.

**Comment by josephjclark** [comment]
API Design notes (this is me thinking aloud). To be discussed.

Clients:

* Build scripts which run at build time and setup a "static" database to be used by apollo at runtime
  *  But we want to decouple the database from the build, right?
  * When, how and where do we update the database?
  * Even in a decoupled architecture we need some form of versioning (I don't know about this stuff, lets get an adult to help)
* Live runtime services which generate embeddings on the fly (ie user queries), integrated into app.openfn.org
  * Each service is a different python service on apollo, eg, job_chat, mappings, adaptor_generator, docs_search
* Totally offline scripts run ad-hoc by humans, ie, generate mappings for Aisha
  * These surely use the CLI and apollo though?
* Testing/research notebooks in Apollo, for devs?

Requirements:

* I need to generate a set of embeddings from a pretty arbitrary set of strings/docs
  * Eg search queries from users (`what is salesforce` or `how do I use lazy state`)
  * Eg SNOMED codes
  * Eg commcare form inputs
* I need to be able to choose my embedding model/service for those strings
* I need to be able to search my embeddings for matches
* I need to be able to remove embeddings at some point, eg, when I update the docsite I blat version A and upload version B instead

Thoughts:

* For any service that allows embed + search, the same embedding service must be used. There's a coupling here.
* Should we couple an Apollo build to a particular DB? So that each  build uses siloed embeddings, and the DBs can be removed when the image is taken offline?

Here's a suggested API which creates a store and couples it to both a database collection and an embedding service.
```
store = getStore(name, embeddings) # creates if doesn't exist. Assumes a database. Accepts an embedding function.

store.add(docs) # embed and save strings/docs. Do we need a collection name WITHIN the store?
store.search(string, options) # accepts strings not embeddings?
store.clear() ?? # Remove everything? Take a query? Take ids, or collection name, or date?
```

We could add a CLI API on top, but for who?

Do we have any way of slicing up a collection? Is LOINC one collection and SNOMED another? Or is Mappings a collection which has a LOINC "slice" and a snomed "slice" (idk how databases and tables map yet)

**Comment by josephjclark** [comment]
Update from meeting with @hanna-paasivirta:

A couple of important things came out:

1. Each "store" is a wrapper around some corpus of data. All stores use the same database, but have different embeddings functions and connection options and stuff. We'd have a store for the docsite, loinc, snomed, etc.
1. A store has two responsibilites:
  a) to connect and manage a collection within the database (not at build or runtime, but as some offline process, ie `openfn apollo build-store loinc` will run a build script in the loinc store
  b) to provide a clean `search()` API to client modules who want to use that corpus

So the embedding service is a bunch of helper functions which make it easy for each store to set itself up, abstracting common functionality away and using langchain and setting up the database.

And each store is basically a pair of `setup()` and `search()` functions which are easily called externally.

Here's a sketch of how the filesystem might look:

![Image](https://github.com/user-attachments/assets/9da091d8-e025-47aa-a16a-f43d7fb7646f)


Hanna TODOs:
* Rename functions (shorter, cleaner names)
* Build a dumb demo folder using the common functions

**Comment by josephjclark** [comment]
![Image](https://github.com/user-attachments/assets/bb230eec-b265-46f9-8eeb-ab6c95879885)
