### ISSUE TITLE
code_generator: Logger calls for an unknown attribute 'generate'.

### ISSUE THREAD

**Issue by SatyamMattoo** [OpenFn/apollo#70]
The current code generation service uses `logger.generate` to create logs. On `openfn apollo code_generator tmp/data.json -o tmp/output.json` it returns an error message:

![Screenshot 2024-06-10 181421](https://github.com/OpenFn/apollo/assets/96661612/33e40148-c5e0-4db4-b785-1f5d08d7242d)

A simple fix would be to use `logger.info` or `logger.debug` to avoid this error and print logs successfully.

**Comment by josephjclark** [comment]
That's a typo or find/replace fail something - logger.generate isn't a real log function. Looks like I last touched it a month ago :blush: 

PRs always welcome!
